version: '3.8'

services:
  app:
    image: cti_server
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      args: []
    command: [/app/bin/cti_server]
    init: true
    ports:
      - 3000:3000
    environment:
      PORT: "3000"
      HOST_IP: "0.0.0.0"
      DATABASE_URL: postgres://cti_user:example@db:5432/cti_dev_diesel
    depends_on:
      db:
        condition: service_healthy
    networks: [dbnet]

  # https://hub.docker.com/_/postgres
  db:
    image: postgres
    init: true
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: cti_user
      POSTGRES_PASSWORD: example
      POSTGRES_DB: cti_dev
      # POSTGRES_INITDB_ARGS: "--data-checksums"
      PGDATA: /pgdata
    volumes:
      - ./tmp/pgdata:/pgdata
    networks: [dbnet]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 3s
      retries: 3

networks:
  dbnet:
