# fly.toml app configuration file generated for cti on 2023-05-26T11:03:37+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cti"
primary_region = "fra"
kill_signal = "SIGINT"
kill_timeout = "16s"

[experimental]
  auto_rollback = true

[build]
  dockerfile = "Dockerfile"
  build-target = "production"

[env]
  DATABASE_POOL_SIZE = "100"
  HOST_IP = "0.0.0.0"
  PORT = "3000"
  RUST_BACKTRACE = "full"
  RUST_LOG = "info"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
    [services.ports.tls_options]
      alpn = ["h2", "http/1.1"]
      versions = ["TLSv1.2", "TLSv1.3"]
  [services.concurrency]
    type = "connections"
    hard_limit = 250
    soft_limit = 200

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 3
