// @generated automatically by Diesel CLI.

diesel::table! {
    use diesel::sql_types::*;

    /// Representation of the `captures` table.
    ///
    /// (Automatically generated by Diesel.)
    captures (ip) {
        /// The `ip` column of the `captures` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        ip -> Int4,
        /// The `blck` column of the `captures` table.
        ///
        /// Its SQL type is `Int2`.
        ///
        /// (Automatically generated by Diesel.)
        blck -> Int2,
        /// The `nick` column of the `captures` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        nick -> Text,
        /// The `claimed_at` column of the `captures` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        claimed_at -> Timestamptz,
    }
}

diesel::table! {
    use diesel::sql_types::*;

    /// Representation of the `timestamps` table.
    ///
    /// (Automatically generated by Diesel.)
    timestamps (id) {
        /// The `id` column of the `timestamps` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Varchar,
        /// The `stamped_at` column of the `timestamps` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        stamped_at -> Timestamptz,
    }
}

diesel::allow_tables_to_appear_in_same_query!(captures, timestamps,);
