[package]
name = "cti_core"
description.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = ["parking_lot", "tracing"]

parking_lot = [
  "dep:parking_lot",                 # when feature and dep have same name, use `dep:`
  "once_cell/parking_lot",
  "tokio/parking_lot",
  "tracing-subscriber?/parking_lot", # it's an optional dep, so use `?`
]
tracing = ["dep:tracing", "tracing-subscriber", "tokio/tracing"]

[dependencies]
cti_constants = { path = "../cti_constants" }
cti_types = { path = "../cti_types" }
cti_env = { path = "../cti_env" }
cti_schema = { path = "../cti_schema" }
cti_assets = { path = "../cti_assets" }

axum = { version = "0.6.1", features = ["headers", "http2", "macros", "ws"] }
chrono = "0.4.23"
color-eyre = "0.6.2"
concat-idents = "1.1.4"
deadpool = { version = "0.9.5", features = ["rt_tokio_1"] }
deadpool-diesel = { version = "0.4.1", features = [] }
deadpool-sync = "0.1.0"
diesel = { version = "2.0.2", features = ["chrono"] }
# diesel-async = { version = "0.1.1", features = ["deadpool", "postgres"] }
# git version provides .new_with_setup, 0.1.1 does not have it yet
diesel-async = { git = "https://github.com/weiznich/diesel_async", features = [
  "deadpool",
  "postgres",
] }
diesel_logger = "0.2.0"
fakedata_generator = "0.2.4"
forwarded-header-value = "0.1.1"
futures = "0.3.25"
hyper = { version = "0.14.23", features = ["full"] }
indexmap = { version = "1.9.2", features = ["std"] }
indoc = "1.0.7"
log = "0.4.17"
mime_guess = "2.0.4"
once_cell = "1.16.0"
parking_lot = { version = "0.12.1", optional = true }
rustls = "0.20.7"
serde = { version = "1.0.151", features = ["derive"] }
serde_json = "1.0.89"
serde_with = { version = "2.1.0", features = ["chrono"] }
tokio = { version = "1.23.0", features = ["full"] }
tokio-graceful-shutdown = "0.11.1"
tokio-postgres = "0.7.7"
tokio-postgres-rustls = "0.9.0"
tower = { version = "0.4.13", features = ["full", "tokio", "tokio-stream"] }
tower-default-headers = "0.1.1"
tower-http = { version = "0.3.5", features = ["full", "async-compression"] }
tracing = { version = "0.1.37", optional = true }
tracing-subscriber = { version = "0.3.16", features = [
  "env-filter",
  "json",
], optional = true }
url = "2.3.1"
urlencoding = "2.1.2"
webpki-roots = "0.22.6"

[target.'cfg(target_os = "linux")'.dependencies]
nix = "0.26.1"
privdrop = "0.5.2"
