DROP MATERIALIZED VIEW ranking_all_time;
DROP MATERIALIZED VIEW ranking_year;
DROP MATERIALIZED VIEW ranking_month;
DROP MATERIALIZED VIEW ranking_week;
DROP MATERIALIZED VIEW ranking_day;
DROP MATERIALIZED VIEW ranking_hour;
